# Data Loading

In [39]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [40]:
df = pd.read_csv("student-lifestyle-and-stress-dataset.csv")
df.head()

,Student_Type,Sleep_Hours,Study_Hours,Social_Media_Hours,Attendance,Exam_Pressure,Family_Support,Month,Stress_Level
0,school,6.868702,1.711722,3.176942,NaN,8.0,7.0,2.0,1
1,school,8.519088,3.251084,3.880787,93.978465,6.0,4.0,3.0,1
2,college,4.498770,6.306885,2.936172,64.421253,7.0,1.0,12.0,1
3,school,8.591223,2.384922,5.222832,81.868960,2.0,7.0,7.0,0
4,college,5.329293,9.345179,7.815869,85.847982,5.0,6.0,10.0,1

In [41]:
df.tail()

,Student_Type,Sleep_Hours,Study_Hours,Social_Media_Hours,Attendance,Exam_Pressure,Family_Support,Month,Stress_Level
25495,college,7.803069,7.328193,2.018277,75.435607,5.0,1.0,12.0,0
25496,school,6.734607,2.680109,3.355559,63.387386,8.0,9.0,2.0,1
25497,college,7.701671,2.631250,2.948252,79.818930,4.0,3.0,4.0,1
25498,school,5.903426,3.450424,6.823894,96.680773,2.0,6.0,6.0,0
25499,college,7.419726,6.442748,3.356066,81.452460,9.0,5.0,6.0,1

In [42]:
df.sample(4)

,Student_Type,Sleep_Hours,Study_Hours,Social_Media_Hours,Attendance,Exam_Pressure,Family_Support,Month,Stress_Level
7952,college,6.545667,7.545742,4.454702,NaN,7.0,5.0,NaN,1
17353,college,7.742001,6.244590,7.255347,71.143327,6.0,9.0,9.0,0
12720,college,5.786552,3.443917,3.418414,60.544987,4.0,5.0,11.0,0
15405,college,8.986978,5.424865,3.826770,77.764833,5.0,6.0,1.0,0

# Data Understanding

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25500 entries, 0 to 25499
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Student_Type        24248 non-null  object
 1   Sleep_Hours         24167 non-null  float64
 2   Study_Hours         24223 non-null  float64
 3   Social_Media_Hours  24188 non-null  float64
 4   Attendance          24195 non-null  float64
 5   Exam_Pressure       24230 non-null  float64
 6   Family_Support      24209 non-null  float64
 7   Month               24186 non-null  float64
 8   Stress_Level        25500 non-null  int64
dtypes: float64(7), int64(1), object(1)
memory usage: 1.8+ MB

In [44]:
df.describe()

,Sleep_Hours,Study_Hours,Social_Media_Hours,Attendance,Exam_Pressure,Family_Support,Month,Stress_Level
count,24167.000000,24223.000000,24188.000000,24195.000000,24230.000000,24209.000000,24186.000000,25500.000000
mean,6.458948,4.696477,3.555614,81.270961,5.369748,5.798298,6.500992,0.299882
std,1.504228,2.240148,1.901528,12.052045,2.394003,2.232371,3.455308,0.458215
min,2.008586,-1.433434,0.000040,-5.000000,1.000000,1.000000,1.000000,0.000000
25%,5.438360,3.078230,2.152249,73.738894,4.000000,4.000000,3.000000,0.000000
50%,6.542566,4.538138,3.500709,81.942959,5.000000,6.000000,6.000000,0.000000
75%,7.531571,6.135670,4.864312,90.106859,7.000000,7.000000,10.000000,1.000000
max,9.997527,22.444460,9.962134,120.000000,10.000000,10.000000,12.000000,1.000000

In [45]:
df.dtypes

Student_Type           object
Sleep_Hours           float64
Study_Hours           float64
Social_Media_Hours    float64
Attendance            float64
Exam_Pressure         float64
Family_Support        float64
Month                 float64
Stress_Level            int64
dtype: object

In [46]:
df.shape

(25500, 9)

In [47]:
df.size

229500

In [48]:
df.value_counts()

Student_Type     Sleep_Hours  Study_Hours  Social_Media_Hours  Attendance  Exam_Pressure  Family_Support  Month  Stress_Level
college          2.020814     8.678260     6.683504            96.230350   5.0            8.0             12.0   1               1
school           7.326662     5.634190     2.081646            98.529150   2.0            9.0             11.0   0               1
                 7.328324     5.089045     5.203096            89.309915   6.0            4.0             3.0    0               1
                 7.328338     0.805582     3.588498            98.975980   5.0            9.0             7.0    0               1
                 7.328716     1.532041     5.610477            89.682330   4.0            7.0             12.0   0               1
                                                                                                                                ..
college          6.689947     8.029506     4.757296            74.453451   7.0            7.0             8.0    0               1
                 6.690261     3.830646     2.564738            77.896127   5.0            9.0             12.0   0               1
                 6.690780     3.548993     4.059802            90.856986   9.0            7.0             9.0    1               1
                 6.690846     10.120175    3.791524            90.408269   1.0            10.0            12.0   0               1
working_student  9.900778     6.609219     0.726240            78.382724   9.0            1.0             9.0    1               1
Name: count, Length: 16809, dtype: int64

In [49]:
df.sample(4)

,Student_Type,Sleep_Hours,Study_Hours,Social_Media_Hours,Attendance,Exam_Pressure,Family_Support,Month,Stress_Level
4621,college,3.200044,5.901947,5.816641,64.355695,3.0,6.0,9.0,0
4257,college,7.862774,6.562655,3.763152,73.725745,1.0,2.0,2.0,0
2873,school,8.171372,4.019973,3.783110,86.692350,4.0,7.0,5.0,0
6528,school,9.161596,6.675956,0.975721,91.607835,5.0,3.0,11.0,0

In [50]:
# df.plot.line(x="Student_Type", y="Stress_Level")

In [51]:
df.value_counts(dropna=False)

Student_Type  Sleep_Hours  Study_Hours  Social_Media_Hours  Attendance  Exam_Pressure  Family_Support  Month  Stress_Level
college       5.474364     NaN          1.967293            72.122218   8.0            10.0            12.0   1               2
school        5.172729     NaN          3.635343            72.431862   7.0            6.0             4.0    0               2
              7.462920     NaN          2.996539            83.395148   6.0            5.0             7.0    0               2
              8.036559     NaN          2.692154            65.579372   1.0            9.0             6.0    0               2
college       7.939098     NaN          1.499054            77.302292   9.0            6.0             4.0    1               2
                                                                                                                             ..
              6.971812     5.139169     1.094323            NaN         4.0            3.0             3.0    0               1
              6.971212     7.577539     4.040956            83.898582   5.0            8.0             8.0    0               1
              6.971073     2.669661     6.944191            69.523733   7.0            6.0             9.0    0               1
              6.970846     3.987196     5.105002            83.903769   5.0            10.0            10.0   0               1
NaN           NaN          NaN          5.368300            71.294286   3.0            5.0             6.0    1               1
Name: count, Length: 25476, dtype: int64

In [52]:
df.corr(numeric_only=True)

,Sleep_Hours,Study_Hours,Social_Media_Hours,Attendance,Exam_Pressure,Family_Support,Month,Stress_Level
Sleep_Hours,1.000000,-0.242291,-0.002834,0.005086,0.004067,-0.005918,-0.007994,-0.145736
Study_Hours,-0.242291,1.000000,0.014308,-0.006277,-0.001768,0.013393,0.004135,0.215776
Social_Media_Hours,-0.002834,0.014308,1.000000,0.002018,-0.009236,0.007981,-0.003502,0.089968
Attendance,0.005086,-0.006277,0.002018,1.000000,0.002260,0.002357,0.001382,-0.032811
Exam_Pressure,0.004067,-0.001768,-0.009236,0.002260,1.000000,-0.005430,0.012626,0.519061
Family_Support,-0.005918,0.013393,0.007981,0.002357,-0.005430,1.000000,-0.010970,-0.107542
Month,-0.007994,0.004135,-0.003502,0.001382,0.012626,-0.010970,1.000000,-0.049948
Stress_Level,-0.145736,0.215776,0.089968,-0.032811,0.519061,-0.107542,-0.049948,1.000000

# Data cleaning

In [53]:
df.sample(5)

,Student_Type,Sleep_Hours,Study_Hours,Social_Media_Hours,Attendance,Exam_Pressure,Family_Support,Month,Stress_Level
8131,college,9.144070,2.803260,1.948643,78.188115,6.0,8.0,12.0,0
16289,college,4.418094,5.251229,4.301344,99.125240,3.0,3.0,1.0,0
7785,college,7.367208,6.435656,NaN,75.376934,8.0,4.0,12.0,1
9277,NaN,4.540331,6.267726,2.782067,73.645149,7.0,NaN,12.0,1
4970,working_student,3.804887,3.853424,NaN,89.139240,4.0,8.0,9.0,0

In [54]:
df.duplicated().sum()

np.int64(24)

In [55]:
df = df.drop_duplicates()

In [56]:
df.sample(5)

,Student_Type,Sleep_Hours,Study_Hours,Social_Media_Hours,Attendance,Exam_Pressure,Family_Support,Month,Stress_Level
12336,college,NaN,4.491039,1.531900,68.897840,1.0,8.0,9.0,0
4650,school,7.503080,NaN,6.775778,79.272722,6.0,7.0,12.0,0
18145,college,5.937933,4.637926,3.084132,78.488236,5.0,7.0,12.0,0
18969,college,6.425722,4.781286,1.494458,83.272334,5.0,7.0,12.0,0
7062,college,6.346299,5.215535,3.850435,82.329468,NaN,4.0,6.0,0

In [57]:
df.duplicated().sum()

np.int64(0)

In [58]:
df.columns.to_list()

['Student_Type',
 'Sleep_Hours',
 'Study_Hours',
 'Social_Media_Hours',
 'Attendance',
 'Exam_Pressure',
 'Family_Support',
 'Month',
 'Stress_Level']

In [59]:
# i think if col names is lower i is easier to work with
df.columns = df.columns.str.lower()

In [60]:
df.sample(3)

,student_type,sleep_hours,study_hours,social_media_hours,attendance,exam_pressure,family_support,month,stress_level
9904,college,2.565373,5.241682,3.158933,91.059189,6.0,7.0,7.0,0
8093,school,6.109171,2.207339,2.811875,59.837684,4.0,7.0,11.0,0
1571,working_student,4.304105,7.248486,NaN,92.676146,4.0,7.0,4.0,1

In [61]:
df.isna().sum()

student_type          1251
sleep_hours           1333
study_hours           1253
social_media_hours    1310
attendance            1304
exam_pressure         1270
family_support        1290
month                 1314
stress_level             0
dtype: int64

In [62]:
df.isna().mean()*100

student_type          4.910504
sleep_hours           5.232376
study_hours           4.918355
social_media_hours    5.142095
attendance            5.118543
exam_pressure         4.985084
family_support        5.063589
month                 5.157796
stress_level          0.000000
dtype: float64

In [63]:
# virtually every column has 5 % missing NaN value, i think this is a very subset of the dateset, so it is i think need to be filled.

In [64]:
df.dtypes

student_type           object
sleep_hours           float64
study_hours           float64
social_media_hours    float64
attendance            float64
exam_pressure         float64
family_support        float64
month                 float64
stress_level            int64
dtype: object

In [65]:
df.columns.to_list()

['student_type',
 'sleep_hours',
 'study_hours',
 'social_media_hours',
 'attendance',
 'exam_pressure',
 'family_support',
 'month',
 'stress_level']

In [72]:
# median is good to fill with

floating_cols = [
 'sleep_hours',
 'study_hours',
 'social_media_hours',
 'attendance',
 'exam_pressure',
 'family_support',]

for col in floating_cols:
    df[col] = df[col].fillna(df[col].median())
print("Floating columns NaN values are filled with median of that columns.")

Floating columns NaN values are filled with median of that columns.

In [73]:
df.isna().sum()

student_type          1251
sleep_hours              0
study_hours              0
social_media_hours       0
attendance               0
exam_pressure            0
family_support           0
month                 1314
stress_level             0
dtype: int64

In [74]:
# filling month with median is not good as its meadian is 6 7 month - june, july. Filling them with mode is better i think. 
df["month"].mode()

0    3.0
Name: month, dtype: float64

In [76]:
df["month"] = df["month"].fillna(df["month"].median())
print("Month NaN values are filled with Mode(3.0 - March)")

Month NaN values are filled with Mode(3.0 - March)

In [77]:
df.isna().sum()

student_type          1251
sleep_hours              0
study_hours              0
social_media_hours       0
attendance               0
exam_pressure            0
family_support           0
month                    0
stress_level             0
dtype: int64

In [78]:
df.student_type.dtype

dtype('O')

In [81]:
df.student_type.value_counts()

student_type
college            13379
school              6012
working_student     4834
Name: count, dtype: int64

In [86]:
df['student_type'] = df['student_type'].fillna(df['student_type']).mode()[0]
print("Student_type NaN values are filled with Mode(college)")

Student_type NaN values are filled with Mode(college)

In [89]:
df.isna().sum(), df.dtypes

(student_type          0
 sleep_hours           0
 study_hours           0
 social_media_hours    0
 attendance            0
 exam_pressure         0
 family_support        0
 month                 0
 stress_level          0
 dtype: int64,
 student_type           object
 sleep_hours           float64
 study_hours           float64
 social_media_hours    float64
 attendance            float64
 exam_pressure         float64
 family_support        float64
 month                 float64
 stress_level            int64
 dtype: object)

In [90]:
df.sample(5)

,student_type,sleep_hours,study_hours,social_media_hours,attendance,exam_pressure,family_support,month,stress_level
18348,college,6.377380,6.003180,2.903799,64.107319,7.0,6.0,5.0,0
19999,college,5.666306,4.098422,4.413982,92.029394,5.0,6.0,9.0,0
9593,college,3.893415,6.960972,4.647623,78.298607,5.0,7.0,2.0,1
11491,college,4.894135,8.306984,4.684842,90.445689,8.0,4.0,8.0,1
23614,college,7.990200,7.861148,4.882519,84.429858,2.0,6.0,6.0,0

In [94]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 25476 entries, 0 to 25499
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   student_type        25476 non-null  object
 1   sleep_hours         25476 non-null  float64
 2   study_hours         25476 non-null  float64
 3   social_media_hours  25476 non-null  float64
 4   attendance          25476 non-null  float64
 5   exam_pressure       25476 non-null  float64
 6   family_support      25476 non-null  float64
 7   month               25476 non-null  float64
 8   stress_level        25476 non-null  int64
dtypes: float64(7), int64(1), object(1)
memory usage: 1.9+ MB

In [96]:
df.month.value_counts().sort_values()

month
9.0     1965
1.0     1985
4.0     1985
11.0    2003
7.0     2016
10.0    2019
8.0     2021
2.0     2026
5.0     2042
12.0    2049
3.0     2062
6.0     3303
Name: count, dtype: int64

In [97]:
# i think month must be as its name like categorical not numbers, so it is better to move them to month
month_map = {
    1: 'January',   2: 'February',  3: 'March',
    4: 'April',     5: 'May',       6: 'June',
    7: 'July',      8: 'August',    9: 'September',
    10: 'October',  11: 'November', 12: 'December'
}
df['month'] = df['month'].astype(int).map(month_map)
print("Month numbers transferred to categories.")

Month numbers transferred to categories.

In [98]:
df.dtypes

student_type           object
sleep_hours           float64
study_hours           float64
social_media_hours    float64
attendance            float64
exam_pressure         float64
family_support        float64
month                  object
stress_level            int64
dtype: object

In [99]:
df.sample(3)

,student_type,sleep_hours,study_hours,social_media_hours,attendance,exam_pressure,family_support,month,stress_level
2125,college,7.247541,4.538138,8.584068,63.604694,6.0,3.0,April,1
21304,college,4.472985,8.220870,5.294843,89.187708,5.0,6.0,July,1
3699,college,6.336811,8.354281,2.744166,88.218864,8.0,7.0,June,1

# EDA(Exploratory Data Analysis)

In [100]:
df.head(3)

,student_type,sleep_hours,study_hours,social_media_hours,attendance,exam_pressure,family_support,month,stress_level
0,college,6.868702,1.711722,3.176942,81.941554,8.0,7.0,February,1
1,college,8.519088,3.251084,3.880787,93.978465,6.0,4.0,March,1
2,college,4.498770,6.306885,2.936172,64.421253,7.0,1.0,December,1

In [101]:
df.describe()

,sleep_hours,study_hours,social_media_hours,attendance,exam_pressure,family_support,stress_level
count,25476.000000,25476.000000,25476.000000,25476.000000,25476.000000,25476.000000,25476.000000
mean,6.463091,4.688690,3.552719,81.302928,5.351311,5.807976,0.299851
std,1.464487,2.184630,1.852293,11.740114,2.334919,2.175324,0.458201
min,2.008586,-1.433434,0.000040,-5.000000,1.000000,1.000000,0.000000
25%,5.510233,3.157381,2.234549,74.280603,4.000000,4.000000,0.000000
50%,6.542207,4.538138,3.501057,81.941554,5.000000,6.000000,0.000000
75%,7.473658,6.035742,4.774688,89.580536,7.000000,7.000000,1.000000
max,9.997527,22.444460,9.962134,120.000000,10.000000,10.000000,1.000000